---
- name: Include sshd configuration tasks
  ansible.builtin.include_tasks: sshd.yml

- name: Include sysctl hardening tasks
  ansible.builtin.include_tasks: sysctl.yml

- name: Include journal rotate tasks
  ansible.builtin.include_tasks: journal_rotate.yml